language: java
install: true


dist: trusty
jdk:
  - openjdk13


branches:
  only:
  - master
  - v7.6.0
    

script:
  - ./gradlew :server:test --tests 'org.elasticsearch.modules.reindex.*'
  - ./gradlew :server:test --tests 'org.elasticsearch.modules.percolator.*'
  - ./gradlew :server:test --tests 'org.elasticsearch.modules.ingest-geoip.*'
  - ./gradlew :server:test --tests 'org.elasticsearch.modules.rank-eval.*'