language: java
install: true


dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk13
  - openjdk-ea


matrix:
  allow_failures:
    - jdk: openjdk-ea

branches:
  only:
  - master
  - v7.6.0
    

script:
  - ./gradlew --continue clean build --scan -s -p modules/