language: java
install: true


dist: trusty
jdk:
  - openjdk13


branches:
  only:
  - master
  - v7.6.0
    

script:
  - cd modules
  - cd reindex
  - ../../gradlew test
  - echo 'Reindex tests success'
  - cd ..
  - cd percolator
  - ../../gradlew test
  - echo 'Percolator tests success'
  - cd ..
  - cd ingest-geoip
  - ../../gradlew test
  - echo 'Ingest-geoip tests success'
  - cd ..
  - cd rank-eval
  - ../../gradlew test
  - echo 'Rank-eval tests success'
  - cd ..
  - cd ..
  - ./gradlew modules:ingest-user-agent:test