language: java
install: true
dist: trusty
jdk:
- openjdk13
branches:
  only:
  - master
  - v7.6.0
script:
  - ./gradlew modules:reindex:test
  - ./gradlew modules:percolator:test
  - ./gradlew modules:ingest-geoip:test
  - ./gradlew modules:rank-eval:test
