language: java
install: true
dist: trusty
jdk:
- openjdk13
branches:
  only:
  - master
  - v7.6.0
script:
- ./gradlew modules:ingest-user-agent:test
deploy:
  provider: heroku
  api_key:
    secure: "nwD5YQsRdpJGKVbSh9TIpIkR4JZVGz71jB7EQ8Yb55RT0XgGlbp4phw8vzPMyURGZxWqlZAqsn1Cjzx2qPGh85l2O1FwtCfneywzR54CUe3+wAtnYlHCFEy8OSnx6/dpoXsYj4b2lmFsgxyA5kCrs+Yi0h6x+dFFtRRXDeFdmrvRogRY/yeTw73feJ8frQdx9OO/FBNG0BrG4ktqlecdnRAz0I4/SXwJVrH3V1gMHVM2PagH6+aSODRx3wMS9ir6LxaZRv2gQsotN+u64Ey9TxOUMLyv8q4tarhYnT7/G9ToH5DKM6ycv+DKOKS+JPuo5W1c1FfaHzBTRhb9JuYS50Ttefc2NtYAW+IKNyLxvADKOqxw1tgZwL+ys/BIz6uFNBgcOi25HGp7SB+f9pfa1ZryQ6zF34ns+NWPj89ix056cQAt1ajgOkHH/uFSoZ0ape94cA4YpvVnq4LSGCMwSvp0wZiCqVXdWud/uf52jrg7GMlZi0rtEbybUOOJgKAXWkTYrKWCtVUmoAH1Ak/qhxt7JCudT1GLoV0/jGPYvei3WNfV7qWM/lozQkIXNT3ndXOQjXLlYHfLvQND0HfS4xVen1MI6tZJSXHGOowsxSmmpIG20R1E2iDqRjfzecosdItjz2BLXRbs6rFFXZ05icFGJWsPk6e5WKmBaoNc/m8="
