language: java
install: true
dist: trusty
jdk:
- openjdk13
branches:
  only:
  - master
  - v7.6.0
script: 
deploy:
  provider: heroku
  api_key:
    secure: AZEh8F70tMGKObHuOeZSa0ignQS5ci7EghG9HnPj14AiXybO1zbfyGNl6ar7qyiNTlQFsWLDEtdl6umhLRKLsYv8nQQgYlTrMD4iqpQ2KycAUHSJ95yQbEOY8/uSFQtvibBYZ+70OlgCWysZHfyd7fmNhw4/2X17uY2vnaxLi0LjTZ7Rn2CzbhsWVjsZSWsNIUlwvFGfusXGpAnG2oDpkf3EkRMVzRduaid1gEbOIJsEHaJiAF/pEkyNt5qSVHcxaI+FOhk0tyyMsoMLJX50BBpYZ4rKtgb6twtrlIUzlXX+KfKtPaE8XD6ol89rAi+qQX1UeUhg+PUB3R/bnRXExRclVjc5GmLj6HsXteLgTUu5zFL2vjd7EmuA76wbDlZJ3PcaQ8IvcshHfe3Su2sjf0pFmC0t2MQNKy140JlScg5fwWFvc6QPWF+m1hz5Q4w7ozxmdyQ+2i4tpLU4Zun5btW5x6n2f3CfPIXZ8xfCC9KdofFX7VZqAnYWbRQPaeWiHmvFI3cRaWWWwtfAGmcksvlRdS1+Acun9IOywEXLQuryaVwTTB1dPCNhmrb5lmRVdHsml6f7KuggrofCn9ZHwzYP+LSuKHNlQqf7gEWVMkAdvwqHvXkboj9TXcP8ddAjeznSzpByg5Mekb8aCy6TLT1WrHyIr+xxtyHPRwWkEP8=
