language: java
install: true
dist: trusty
jdk:
- openjdk13
branches:
  only:
  - master
  - v7.6.0
script:
- "./gradlew modules:ingest-user-agent:test"
deploy:
  provider: heroku
  api_key:
    secure: W24LdzaV21xRe52DCO9gtvuF7Y2qWdKa8wM4FwlMC82OgmIFVM1e6vwJqOSyeADg+QZWFXu02zFdSg3pEaeVkevp8UqRhm6jlbkhz7pStA8uHmDlY62qTDzV9mmFh1UgS9pQliUYlv9B4Ovc5IGBvZwfj+g8mcY6PKNsFSsASuC/BZZ67z88CzZLNZwoZI73+Sveei9Ctu36qRb6TI5V43ZNHtuMkOFu4iuRDD1KqxJuwESFB3mX9hMRkm9pUvhQH4r4kuyuhf0ba4wEvoGi4uW6uyNWawo7j1HRXDsS3Ic1oME6hEvkyr5w1UngRxo3kHlLN2BQdp2r34STzKbifq3ez+kJktLgveHY0UEm+TOSeQkqOZnxU72Yz4Ikjtx6WoMivKM5j2UgMOVQgpkImKFYsDWeFcmlI/iq2QO8dQncHIjDLKWnAo1Fc/fFs9PAmNIAYxcOz+gd7kNO0oMdmZ98Ed111TGVEBfTO1RJ0+sQblR9nLhY8YpBQjV6lgss//MQLH6gUc2oWjSIXa8SK4emy+3QsINjCSyvRxxvZNHYbRziuTDwyM+Gj2g/0qKemzh+LwtbsHI8L+u4wWD8GyBbBTd+oeNFxrEj6TBpur5gMWm8bXjK3t1DNJVybmkT8Dlj6XXCvtnq33Iu5tkneCZrsnDqMUI3Yf9uD4zHP7k=
