language: java
install: true
dist: trusty
jdk:
- openjdk13
branches:
  only:
  - master
  - v7.6.0
script:
- "./gradlew modules:ingest-user-agent:test"
deploy:
  provider: heroku
  api_key:
    secure: eh6Oj3ZmBbFAPxNLYOaFaeCij08z+MPQYppSltC+p2gEZklHX0Vt+eeUvXjLtrBmbuHJ9vlJZMeKJmbC8Bl38lY2sJwmBWOMZLpHCdGgXpDPN6yocXmS+KnNLqf6G21kLCiaPBdaPtKugREjO8RJ8jarStcmBrlDkmNNxBzfRj5jFLzwKfeTaCDUwPxOMKaKmnIPzkZGHx3cKsWvqoWF+7s3SSsmGhmUh9lCyryZydD/MlknZbTEiMKXNONlmbrNrjq3j3wR/6yrUc0m++km23oJpsY5VHLFV7CZI2V2ZHFv10jv+R6ZVxFM1NLe3/YqFNUVVQw8coSfwFMr3hhiqfNky1mChwYVWWlfVTehQSc2UFGfu+Y4xLwGpeXYiIWULCL/zTdIBrzUZ0Ga0Pyc5cfF/u3acvfU3BTumOJEXihQTPlrwdIvgIjVq6PXDCZ7JxByeNjrteNvPEMsFvMu20yBXE1Vt/vQ3qsDD7yQM59AN9XFBAdiLqTCpCXaK567twYK/qtMy5vDbQEmKYZ9XC8NniYoTSy9xLGXVmI7FA+y5eHX9XS3o7m74z23K0L4cd3XlewbGj+0Ey31MLaTEjEOleY4i83Adn2Ret39QuPlLV/Qm+5ivfaD4+VwMiS92V8soliWkY/q0Pes0I9RKo1RehYVzi31p6Dk9BRM/Xs=
